### ISSUE TITLE
Create user story

### ISSUE THREAD

**Issue by CaseyQWood** [CaseyQWood/To-Do-List#7]
![Screen Shot 2021-06-25 at 9 29 16 PM](https://user-images.githubusercontent.com/44916074/123501820-710bb680-d5fc-11eb-903e-b819610ff8d6.png)
create a list of the functionalities a user will want/ need

**Comment by jojo2829** [comment]
https://docs.google.com/spreadsheets/d/1uGCcrZdnmJHTNQqloIojDunb0lCBcUCeXdQOP-OiURw/edit?usp=sharing
